/* automatically generated by JSCoverage - do not edit */
if (typeof _$jscoverage === 'undefined') _$jscoverage = {};
if (! _$jscoverage['italian.js']) {
  _$jscoverage['italian.js'] = [];
  _$jscoverage['italian.js'][1] = 0;
  _$jscoverage['italian.js'][8] = 0;
}
_$jscoverage['italian.js'][1]++;
recipe({libraries: ["fettuccine.alfredo", "acqua.pazza"], scripts: []}).then((function () {
  _$jscoverage['italian.js'][8]++;
  console.log("Dig in!");
}));
_$jscoverage['italian.js'].source = ["recipe({","  libraries: [","    \"fettuccine.alfredo\",","    \"acqua.pazza\"","  ],","  scripts: []","}).then(function(){","  console.log(\"Dig in!\");","});"];
