/* automatically generated by JSCoverage - do not edit */
if (typeof _$jscoverage === 'undefined') _$jscoverage = {};
if (! _$jscoverage['menu.mock.js']) {
  _$jscoverage['menu.mock.js'] = [];
}
_$jscoverage['menu.mock.js'].source = [];
