/* automatically generated by JSCoverage - do not edit */
if (typeof _$jscoverage === 'undefined') _$jscoverage = {};
if (! _$jscoverage['recipe.version.js']) {
  _$jscoverage['recipe.version.js'] = [];
  _$jscoverage['recipe.version.js'][1] = 0;
}
_$jscoverage['recipe.version.js'][1]++;
if (! recipe) {
  _$jscoverage['recipe.version.js'][1]++;
  var recipe = (function () {
});
}
_$jscoverage['recipe.version.js'][1]++;
;
_$jscoverage['recipe.version.js'][1]++;
recipe.version = "1388663627840";
_$jscoverage['recipe.version.js'].source = ["if(!recipe){var recipe=function(){}};recipe.version=\"1388663627840\";"];
